Repository MT-Go-likelion/MT-Go-front, pull requests merged in 2023-08, with the labels that each got.

#19 Feature/16 Lodging detail UI
  .yarn/cache/swiper-npm-10.0.4-db9b89fe80-a21f0fc2a8.zip
  .yarn/install-state.gz
  package.json
  src/assets/images/booking.png
  src/assets/images/heart.png
  src/components/Common/CheckBox/CheckBox.jsx
  src/components/Common/Line/HorizonLine.jsx
  src/components/Common/Modal/TermsModal.jsx
  src/components/Common/Review/RatingContainer.jsx
  src/components/ImageSwiper/ImageSwiper.jsx
  src/components/ImageSwiper/styles.css
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignUpForm.jsx
  src/index.js
  src/pages/LodgingDetail.jsx
  src/pages/index.js
  src/styles/GlobalStyle.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#26 Feature/main page
  .eslintrc
  package.json
  src/assets/images/banner-main.png
  src/components/Card/BagCard.jsx
  src/pages/Main.jsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#29 feat: Mypage & teamspacepopup
  src/assets/images/banner-main.png
  src/assets/images/banner.png
  src/components/Popup/TeamspacePopup.jsx
  src/index.js
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/index.js
Labels: ✨ Feature, 🎨 Html&css

#30 API: 회원가입, 로그인, 로그아웃
  .yarn/cache/@tanstack-eslint-plugin-query-npm-4.32.1-3cefa3feb0-a03a7f046b.zip
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-query-core-npm-4.32.1-b5b0ae9ad1-7676e36721.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.32.1-5b867fc27a-a0a48ccce6.zip
  .yarn/cache/@tanstack-react-query-npm-4.32.1-f527d17319-31cdf93896.zip
  .yarn/cache/copy-anything-npm-3.0.5-562d15fb3f-d39f6601c1.zip
  .yarn/cache/is-what-npm-4.1.15-328677a458-fe27f6cd4a.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.13.1-39607ca2e6-9c8c664a92.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  .yarn/install-state.gz
  package.json
  src/App.js
  src/apis/.gitkeep
  src/apis/authAPI.js
  src/components/Navbar/Navbar.jsx
  src/components/SelectBox/Headcount.jsx
  src/components/Sign/InputWithLabel.jsx
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignUpForm.jsx
  src/config/api.js
  src/contexts/.gitkeep
  src/hooks/queries/useSignIn.jsx
  src/hooks/queries/useSignOut.jsx
  src/hooks/queries/useSignUp.jsx
  src/hooks/queries/useUser.jsx
  src/index.js
  src/pages/SignUp.jsx
  src/utils/.gitkeep
  src/utils/userLocalstore.jsx
  yarn.lock
Labels: ✨ Feature, 📬 API

#37 Calendar 컴포넌트 제작
  .yarn/cache/@types-lodash-npm-4.14.196-06373ceef2-201d17c3e6.zip
  .yarn/cache/@types-lodash.memoize-npm-4.1.7-e16866892d-85f128b660.zip
  .yarn/cache/@wojtekmaj-date-utils-npm-1.5.0-1781f0df57-ad0fbb7345.zip
  .yarn/cache/clsx-npm-2.0.0-afafbbe44a-a2cfb2351b.zip
  .yarn/cache/get-user-locale-npm-2.3.0-114f13dd68-8a815e7528.zip
  .yarn/cache/moment-npm-2.29.4-902943305d-0ec3f9c2bc.zip
  .yarn/cache/react-calendar-npm-4.6.0-ffe2621b61-2832d2a468.zip
  .yarn/cache/tiny-warning-npm-1.0.3-750b7a07c4-da62c4acac.zip
  .yarn/install-state.gz
  package.json
  src/components/Calendar/DetailCalendar.jsx
  src/components/Calendar/RegisterCalendar.jsx
  src/components/LodgingDetail/LodgingDetailContent.jsx
  src/pages/Shopping.jsx
  src/styles/Calendar.css
  src/utils/formatPrice.js
  yarn.lock
Labels: ✨ Feature

#40 레크레이션 상세페이지 / 등록페이지 와이어프레임
  .yarn/cache/@toast-ui-editor-npm-3.2.2-8b6a9786fd-b1772a1a15.zip
  .yarn/cache/@toast-ui-react-editor-npm-3.2.3-aed61aa676-5ffd6f9b27.zip
  .yarn/cache/dompurify-npm-2.4.7-9933129008-13c047e772.zip
  .yarn/cache/orderedmap-npm-2.1.1-64b8a0684f-082cf970b0.zip
  .yarn/cache/prosemirror-commands-npm-1.5.2-27f8f3fee9-ff65063a8c.zip
  .yarn/cache/prosemirror-history-npm-1.3.2-cc128c8ee6-b85fe6378a.zip
  .yarn/cache/prosemirror-inputrules-npm-1.2.1-b0e0cd0831-fc414d8376.zip
  .yarn/cache/prosemirror-keymap-npm-1.2.2-efb8276b00-85fe4fc303.zip
  .yarn/cache/prosemirror-model-npm-1.19.3-b34d2aa032-a0c32127df.zip
  .yarn/cache/prosemirror-state-npm-1.4.3-d6540e44ad-28857d935c.zip
  .yarn/cache/prosemirror-transform-npm-1.7.4-83c082ca81-c7ac776f10.zip
  .yarn/cache/prosemirror-view-npm-1.31.7-d5dccb5135-879ebd7105.zip
  .yarn/cache/rope-sequence-npm-1.3.4-3b09587e5f-95cca2f99a.zip
  .yarn/cache/w3c-keyname-npm-2.2.8-66d7d5317a-95bafa4c04.zip
  .yarn/install-state.gz
  package.json
  src/components/Editor/RecreationEditor.jsx
  src/index.js
  src/pages/RecreationDetail.jsx
  src/pages/RecreationRegistration.jsx
  src/pages/index.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#44 feat:teamspace 생성, 링크 연결, popup
  package.json
  src/components/Card/BestlocationCard.jsx
  src/components/Popup/DeleteSharePopup.jsx
  src/components/Popup/TeamspacePopup.jsx
  src/constants/color.js
  src/index.js
  src/pages/Mypage.jsx
  src/pages/MypageTeamspace.jsx
  src/pages/index.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#46 숙소관련 API 연결
  src/App.js
  src/apis/lodgingAPI.js
  src/apis/lodgingReviewAPI.js
  src/components/Card/BestlocationCard.jsx
  src/components/ImageSwiper/ImageSwiper.jsx
  src/components/LodgingDetail/LodgingDetailContent.jsx
  src/components/LodgingDetail/LodgingDetailHeader.jsx
  src/components/LodgingDetail/LodgingDetailReview.jsx
  src/components/Map/LodgingMap.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignUpForm.jsx
  src/config/api.js
  src/hooks/queries/Auth/useSignIn.jsx
  src/hooks/queries/Auth/useSignOut.jsx
  src/hooks/queries/Auth/useSignUp.jsx
  src/hooks/queries/Auth/useUser.jsx
  src/hooks/queries/Lodging/useLodging.jsx
  src/hooks/queries/Lodging/useLodgingDetail.jsx
  src/hooks/queries/Lodging/useLodgingReview.jsx
  src/index.js
  src/pages/CreateLodging.jsx
  src/pages/CreateRoom.jsx
  src/pages/Error.jsx
  src/pages/Loading.jsx
  src/pages/Lodging.jsx
  src/pages/LodgingDetail.jsx
  src/pages/index.js
Labels: ✨ Feature, 📬 API

#50 리뷰 API 수정사항 반영
  src/apis/lodgingReviewAPI.js
  src/components/LodgingDetail/LodgingDetailReview.jsx
  src/config/api.js
  src/hooks/queries/Lodging/useLodging.jsx
  src/hooks/queries/Lodging/useLodgingReview.jsx
  src/pages/CreateLodging.jsx
  src/pages/LodgingDetail.jsx
  src/pages/RecreationRegistration.jsx
Labels: 🔨 Refactor, 📬 API

#51 장바구니 UI
  src/assets/images/ShoppingMain.png
  src/components/Button/ShoppingTag.jsx
  src/components/Button/SubmitButton.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/Popup/Mypage/DeleteSharePopup.jsx
  src/components/Popup/Mypage/TeamspacePopup.jsx
  src/components/Popup/Shopping/TagPopup.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/MypageTeamspace.jsx
  src/pages/Shopping.jsx
Labels: ✨ Feature, 🎨 Html&css

#58 수정 삭제 기능 수정
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/Popup/Shopping/CreatePopup.jsx
  src/components/Popup/Shopping/TagPopup.jsx
Labels: ✨ Feature, 🎨 Html&css

#60 경고, 오류 메시지 제거 작업
  .yarn/cache/uuid-npm-9.0.0-46c41e3e43-8dd2c83c43.zip
  .yarn/install-state.gz
  package.json
  src/components/Card/BestlocationCard.jsx
  src/components/Card/RecreationCard.jsx
  src/components/Common/Line/HorizonLine.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/LodgingDetail/LodgingDetailContent.jsx
  src/components/LodgingDetail/LodgingDetailReview.jsx
  src/components/SelectBox/Headcount.jsx
  src/components/SelectBox/Location.jsx
  src/components/SelectBox/Price.jsx
  src/pages/Lodging.jsx
  src/pages/Mypage.jsx
  src/pages/Recreation.jsx
  src/pages/Shopping.jsx
  yarn.lock
Labels: 🐞 BugFix

#62 Feature/fix
  src/components/Button/SubmitButton.jsx
  src/components/Card/BestlocationCard.jsx
  src/components/Card/ShoppingCard.jsx
  src/components/Common/Shopping/ListTable.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/MypageTeamspace.jsx
  src/pages/Shopping.jsx
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#64 feat: Mainpage Mobile
  src/assets/images/MobileBanner.png
  src/components/Card/BagCard.jsx
  src/components/Card/BestlocationCard.jsx
  src/components/Card/RecreationCard.jsx
  src/pages/Main.jsx
  src/pages/Shopping.jsx
  src/styles/GlobalStyle.js
Labels: ✨ Feature, 🎨 Html&css

#67 팀스페이스 api 연결
  src/apis/teamAPI.js
  src/components/Button/TeamLodgingBtn.jsx
  src/components/Card/BestlocationCard.jsx
  src/components/Card/RecreationCard.jsx
  src/components/Common/Shopping/ListTable.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/LodgingDetail/LodgingDetailHeader.jsx
  src/components/Popup/Lodging/LodingPopup.jsx
  src/components/Popup/Mypage/TeamspaceCreatePopup.jsx
  src/components/Popup/Mypage/TeamspaceJoinPopup.jsx
  src/components/Popup/Recreation/RecreationPopup.jsx
  src/config/api.js
  src/hooks/queries/Team/useTeam.jsx
  src/hooks/queries/Team/useTeamLodging.jsx
  src/hooks/queries/Team/useTeamLodgingIsScrap.jsx
  src/hooks/queries/Team/useTeamLodgingScrap.jsx
  src/hooks/queries/Team/useTeamRecreation.jsx
  src/hooks/queries/Team/useTeamRecreationIsScrap.jsx
  src/hooks/queries/Team/useTeamRecreationScrap.jsx
  src/hooks/queries/Team/useTeamShopping.jsx
  src/hooks/queries/Team/useTeamShoppingCreation.jsx
  src/index.js
  src/pages/LodgingDetail.jsx
  src/pages/Mypage.jsx
  src/pages/MypageTeamspace.jsx
  src/pages/Shopping.jsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#71 숙소 리스트 페이지네이션 적용 & 팀스페이스 유저 목록
  .yarn/cache/block-stream-npm-0.0.9-ce3ced9c02-72733cbb81.zip
  .yarn/cache/fstream-npm-1.0.12-db27e8a713-e6998651ae.zip
  .yarn/cache/paginator-npm-1.0.0-96b8778bda-6bbb8c463f.zip
  .yarn/cache/react-js-pagination-npm-3.0.3-aba99bf366-7b5c5420b6.zip
  .yarn/cache/react-npm-16.14.0-932446ec69-8484f3ecb1.zip
  .yarn/cache/rimraf-npm-2.7.1-9a71f3cc37-cdc7f6eacb.zip
  .yarn/cache/tar-npm-2.2.2-0ce6504da4-c0c3727d52.zip
  .yarn/install-state.gz
  package.json
  src/App.js
  src/apis/lodgingAPI.js
  src/apis/teamAPI.js
  src/config/api.js
  src/hooks/queries/Lodging/useLodging.jsx
  src/hooks/queries/Team/useTeamUserList.jsx
  src/pages/Lodging.jsx
  src/pages/MypageTeamspace.jsx
  src/styles/Pagination.css
  yarn.lock
Labels: ✨ Feature, 📬 API

#73 개인/ 팀 스페이스 장보기 목록 담기 API
  src/components/Common/Shopping/ShoppingTable.jsx
  src/hooks/queries/Shopping/useShopping.jsx
  src/pages/Mypage.jsx
  src/pages/Shopping.jsx
Labels: ✨ Feature, 📬 API

#75 레크레이션 모바일
  src/assets/images/LoadgingBackM.png
  src/assets/images/LodgingMobileBack.png
  src/assets/images/folder.png
  src/components/Footer/MobileFooter.jsx
  src/components/Mobile/RecreationMobileCard.jsx
  src/components/Popup/Recreation/RecreationPopup.jsx
  src/pages/Main.jsx
  src/pages/Recreation.jsx
Labels: ✨ Feature, 🎨 Html&css

#82 숙소, 레크레이션, 리뷰 삭제 기능 && 레크레이션, 리뷰 페이지네이션
  src/apis/lodgingAPI.js
  src/apis/lodgingReviewAPI.js
  src/apis/recreationAPI.js
  src/components/Card/BestlocationCard.jsx
  src/components/LodgingDetail/LodgingDetailHeader.jsx
  src/components/LodgingDetail/LodgingDetailReview.jsx
  src/config/api.js
  src/hooks/queries/Lodging/useLodging.jsx
  src/hooks/queries/Lodging/useLodgingDetail.jsx
  src/hooks/queries/Lodging/useLodgingReview.jsx
  src/hooks/queries/Lodging/useLodgingScrap.jsx
  src/hooks/queries/Recreation/useRecreation.jsx
  src/pages/Lodging.jsx
  src/pages/Recreation.jsx
  src/pages/RecreationDetail.jsx
Labels: ✨ Feature, 📬 API

#85 장바구니 페이지 모바일 ui
  src/assets/images/ShoppingMobileBack.png
  src/components/Card/ShoppingCard.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/Popup/Shopping/CreatePopup.jsx
  src/components/Popup/Shopping/TagPopup.jsx
  src/pages/Shopping.jsx
Labels: ✨ Feature, 🎨 Html&css

#93 feat: 레크레이션 디테일 페이지
  src/assets/images/chevron-left.png
  src/pages/RecreationDetail.jsx
Labels: ✨ Feature, 🎨 Html&css

#99 Feature/lodging detail mobile
  src/assets/images/LodgingDetailMobileLike.png
  src/assets/images/LodgingDetailMobileLiked.png
  src/assets/images/LodgingDetailMobileScrap.png
  src/components/Card/BestlocationCard.jsx
  src/components/Common/Review/RatingContainer.jsx
  src/components/LodgingDetail/LodgingDetailHeader.jsx
  src/components/LodgingDetail/LodgingDetailPricetable.jsx
  src/components/LodgingDetail/LodgingDetailReview.jsx
  src/components/LodgingDetail/index.js
  src/components/Map/LodgingMap.jsx
  src/components/Mobile/LodgingMobileCard.jsx
  src/components/Popup/Lodging/LodingPopup.jsx
  src/components/Popup/Shopping/CreatePopup.jsx
  src/config/api.js
  src/pages/Lodging.jsx
  src/pages/LodgingDetail.jsx
  src/styles/Pagination.css
Labels: ✨ Feature, 🎨 Html&css

#102 mobile signin
  src/assets/images/SigninMobile.png
  src/assets/images/SigninMobileWave.png
  src/components/Footer/MobileFooter.jsx
  src/components/Sign/InputWithLabel.jsx
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignWrapper.jsx
  src/config/api.js
  src/pages/Lodging.jsx
  src/pages/SignIn.jsx
Labels: ✨ Feature, 🎨 Html&css

#106 Footer 수정
  src/assets/images/MypageFooter.png
  src/assets/images/ShoppingFooter.png
  src/assets/images/homeFooter.png
  src/assets/images/lodgingFooter.png
  src/assets/images/recreationFooter.png
  src/components/Footer/MobileFooter.jsx
Labels: ✨ Feature, 🎨 Html&css

#110 feat: mainpage, footer, shopping 페이지 수정
  src/assets/images/banner.png
  src/components/Footer/MobileFooter.jsx
  src/pages/Main.jsx
  src/pages/Shopping.jsx
Labels: ✨ Feature, 🎨 Html&css

#113 메인페이지 API 연결 & 기타사항들 작업
  src/apis/lodgingAPI.js
  src/apis/recreationAPI.js
  src/components/Card/BestlocationCard.jsx
  src/components/Card/ShoppingCard.jsx
  src/components/Common/Shopping/ListTable.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/LodgingDetail/LodgingDetailContent.jsx
  src/config/api.js
  src/hooks/queries/Lodging/useLodgingMain.jsx
  src/hooks/queries/Recreation/useRecreationMain.jsx
  src/pages/CreateLodging.jsx
  src/pages/Lodging.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/Recreation.jsx
  src/pages/RecreationRegistration.jsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#117 api 요청 성공 팝업창 적용
  src/components/Button/SubmitButton.jsx
  src/components/Card/BestlocationCard.jsx
  src/components/Card/RecreationCard.jsx
  src/components/Common/Popup/ApiCallSuccessPopup.jsx
  src/components/Common/Shopping/ListTable.jsx
  src/components/Common/Shopping/ShoppingTable.jsx
  src/components/LodgingDetail/LodgingDetailHeader.jsx
  src/components/Popup/Lodging/LodingPopup.jsx
  src/components/Popup/Recreation/RecreationPopup.jsx
  src/components/Popup/Shopping/CreatePopup.jsx
  src/hooks/queries/Team/useTeamLodgingScrap.jsx
  src/pages/CreateLodging.jsx
  src/pages/Mypage.jsx
  src/pages/MypageTeamspace.jsx
  src/pages/Recreation.jsx
  src/pages/RecreationDetail.jsx
  src/pages/RecreationRegistration.jsx
  src/pages/Setting.jsx
Labels: ✨ Feature

#123 Qa/118
  src/apis/recreationAPI.js
  src/components/Card/RecreationCard.jsx
  src/components/Common/Popup/ApiCallErrorPopup.jsx
  src/components/LodgingDetail/LodgingDetailContent.jsx
  src/components/Map/LodgingMap.jsx
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignUpForm.jsx
  src/hooks/queries/Recreation/useRecreationDetail.jsx
  src/pages/CreateLodging.jsx
  src/pages/LodgingDetail.jsx
  src/pages/Recreation.jsx
  src/pages/RecreationDetail.jsx
  src/pages/RecreationRegistration.jsx
  src/pages/UpdateLodging.jsx
  src/pages/UpdateRecreation.jsx
Labels: 🔨 Refactor, ✨ Feature

#124 Feature/116 protect route
  .gitignore
  src/apis/authAPI.js
  src/components/Card/RecreationCard.jsx
  src/components/Common/Modal/SuggestionModal.jsx
  src/components/LodgingDetail/LodgingDetailContent.jsx
  src/components/LodgingDetail/LodgingDetailHeader.jsx
  src/components/Navbar/Navbar.jsx
  src/config/api.js
  src/hooks/queries/Auth/useSuggestion.jsx
  src/index.js
  src/pages/ProtectedRoute.jsx
  src/pages/RecreationDetail.jsx
  src/pages/Shopping.jsx
Labels: ✨ Feature, 📬 API
