Repository MT-Go-likelion/MT-Go-front, pull requests merged in 2023-07, with the labels that each got.

#3 Feat: router 세팅
  .eslintrc.js
  .yarn/cache/@ndelangen-eslint-config-airbnb-npm-14.1.0-2275885849-a9c1cfe5d5.zip
  .yarn/cache/@remix-run-router-npm-1.7.2-f063ddbaf6-ea43bb662f.zip
  .yarn/cache/@types-mime-npm-3.0.1-dec03536dc-4040fac73f.zip
  .yarn/cache/aria-query-npm-5.3.0-76575ac83b-305bd73c76.zip
  .yarn/cache/babel-eslint-npm-10.1.0-6a6d2b1533-bdc1f62b6b.zip
  .yarn/cache/eslint-config-airbnb-base-npm-11.3.2-f8dcfe8f9d-6b902c5dd7.zip
  .yarn/cache/eslint-config-airbnb-base-npm-15.0.0-802837dd26-38626bad2c.zip
  .yarn/cache/eslint-config-airbnb-npm-19.0.4-a73150c84a-253178689c.zip
  .yarn/cache/eslint-config-prettier-npm-8.9.0-55f18738a4-a675d0dabd.zip
  .yarn/cache/eslint-restricted-globals-npm-0.1.1-e145402e72-45433bd3a8.zip
  .yarn/cache/eslint-visitor-keys-npm-1.3.0-c07780a0fb-37a19b712f.zip
  .yarn/cache/react-router-dom-npm-6.14.2-af7ef08cb4-a53dbc566e.zip
  .yarn/cache/react-router-npm-6.14.2-b2944a374e-7507bf5732.zip
  .yarn/cache/resolve-npm-1.22.2-9d9621a4ae-7e5df75796.zip
  .yarn/cache/resolve-patch-f4c4056507-66cc788f13.zip
  .yarn/install-state.gz
  .yarnrc.yml
  package-lock.json
  package.json
  src/App.js
  src/components/.gitkeep
  src/components/Footer.jsx
  src/components/Header.jsx
  src/index.js
  src/pages/.gitkeep
  src/pages/ErrorPage.jsx
  src/pages/Main.jsx
  src/pages/index.js
  yarn.lock
Labels: ✨ Feature

#7 Feature/4 Signup Form UI & 이용약관 모달
  src/assets/images/close.png
  src/assets/images/required.png
  src/components/CheckBox/CheckBox.jsx
  src/components/Modal/TermsModal.jsx
  src/components/Sign/InputWithLabel.jsx
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignUpForm.jsx
  src/components/Sign/SignWrapper.jsx
  src/constants/color.js
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: ✨ Feature, 🎨 Html&css

#6 Feature/3 Login Form UI
  .eslintrc
  .eslintrc.js
  .yarn/cache/@babel-cli-npm-7.22.9-a7e68f0d9c-6acc76e521.zip
  .yarn/cache/@babel-plugin-external-helpers-npm-7.22.5-35c9d0cc36-3cd44da2ef.zip
  .yarn/cache/@babel-plugin-proposal-object-rest-spread-npm-7.20.7-0bc581aa09-1329db1700.zip
  .yarn/cache/@emotion-is-prop-valid-npm-1.2.1-794afe6a94-8f42dc573a.zip
  .yarn/cache/@emotion-memoize-npm-0.8.1-9b1e35ff15-a19cc01a29.zip
  .yarn/cache/@emotion-unitless-npm-0.8.1-bcf0a8f565-385e21d184.zip
  .yarn/cache/@nicolo-ribaudo-chokidar-2-npm-2.1.8-no-fsevents.3-79ca8bfcef-ee55cc9241.zip
  .yarn/cache/@types-stylis-npm-4.2.0-5addc9ed60-02a47584ac.zip
  .yarn/cache/babel-eslint-npm-10.1.0-6a6d2b1533-bdc1f62b6b.zip
  .yarn/cache/camelize-npm-1.0.1-d86ebe085a-91d8611d09.zip
  .yarn/cache/css-color-keywords-npm-1.0.0-fc176df58b-8f125e3ad4.zip
  .yarn/cache/css-to-react-native-npm-3.2.0-46e31a25e3-263be65e80.zip
  .yarn/cache/eslint-visitor-keys-npm-1.3.0-c07780a0fb-37a19b712f.zip
  .yarn/cache/fs-readdir-recursive-npm-1.1.0-258e230a4b-29d50f3d21.zip
  .yarn/cache/make-dir-npm-2.1.0-1ddaf205e7-043548886b.zip
  .yarn/cache/pify-npm-4.0.1-062756097b-9c4e34278c.zip
  .yarn/cache/semver-npm-5.7.2-938ee91eaa-fb4ab5e0dd.zip
  .yarn/cache/shallowequal-npm-1.1.0-6688d419cb-f4c1de0837.zip
  .yarn/cache/slash-npm-2.0.0-69009eac54-512d435073.zip
  .yarn/cache/styled-components-npm-6.0.5-b9b6755f1f-81cc55bb8c.zip
  .yarn/cache/stylis-npm-4.3.0-cec5472bed-6120de3f03.zip
  .yarn/install-state.gz
  package.json
  src/App.css
  src/App.js
  src/assets/images/close.png
  src/assets/images/eye.png
  src/assets/images/eye_blue.png
  src/assets/images/required.png
  src/components/CheckBox/CheckBox.jsx
  src/components/Modal/TermsModal.jsx
  src/components/Sign/InputWithLabel.jsx
  src/components/Sign/SignInForm.jsx
  src/components/Sign/SignUpForm.jsx
  src/components/Sign/SignWrapper.jsx
  src/components/Sign/index.js
  src/constants/color.js
  src/data/.gitkeep
  src/data/hi.js
  src/hooks/.gitkeep
  src/hooks/useInput.jsx
  src/index.css
  src/index.js
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/index.js
  src/styles/GlobalStyle.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#12 Feature/10 App layout
  src/App.js
  src/assets/images/bag.png
  src/components/Footer.jsx
  src/components/Footer/Footer.jsx
  src/components/Header.jsx
  src/components/Navbar/Navbar.jsx
  src/constants/color.js
  src/styles/GlobalStyle.js
Labels: ✨ Feature, 🎨 Html&css

#18 Feature/card compo
  package.json
  src/assets/images/Bag.png
  src/assets/images/Heart.png
  src/assets/images/Recreat.png
  src/assets/images/Select_Bag.png
  src/assets/images/Select_Heart.png
  src/assets/images/Select_recreat.png
  src/assets/images/star.png
  src/components/Card/Bag.jsx
  src/components/Card/Bestlocation.jsx
  src/components/Card/recreation.jsx
  src/constants/color.js
  src/index.js
  src/pages/Room.jsx
  src/pages/index.js
  yarn.lock
Labels: 🎨 Html&css
